server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://175.178.242.121:33060/testing?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 119.29.162.149
    port: 7001
    password: Asdzxc2222
    cluster:
      nodes:
        - 119.29.162.149:7001
        - 119.29.162.149:7002
        - 119.29.162.149:7003
        - 119.29.162.149:7004
        - 119.29.162.149:7005
        - 119.29.162.149:7006
      max-redirects: 3
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    timeout: 10000ms
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug
  pattern:
    dateformat: mm:ss.SSS